config/routes.rb
Foresight::Application.routes.draw do
  devise_for  :users,
              controllers: {omniauth_callbacks: "users/omniauth_callbacks"},
              sign_out_via: [:delete, :get]

  match 'rating' => 'start#rating'

  resources :members, :only => [:index, :create, :destroy, :show] do
    member do
      post 'vote'
      post 'activate'
    end
  end

  get "layout"=> 'start#layout'
  post "participate" => 'members#participate'

  get "/scenarios/:scenario" => redirect('/#scenarios')

  root :to => 'start#index'

end

app/views/layouts/popups/_common.html.haml
.popup#common
  %h2.popup__header Регистрация участника
  .popup__body
    %form{:action => "/", :method => "post"}
      .field
        %label.label{:for => "register-url"} Ссылка на вашу страницу в социальной сети
        .input__wrap
          %input#register-url.input{:name => "url", :type => "text"}
      .field
        %span.label.centered Перейти на страницу в социальной сети
        %ul.socialbuttons
          %li.socialbuttons__item
            %a.vk{:href => "#"}
          %li.socialbuttons__item
            %a.fb{:href => "#"}
      .field
        %label.label{:for => "register-desc"} Ссылка на вашу страницу в социальной сети
        .input__wrap
          %textarea#register-desc.textarea{:name => "url"}
      .submit
        %button.button{:type => "submit"} Зарегистрироваться

app/views/layouts/popups/_message.html.haml
.popup#message
  %h2.popup__header Поздравляем!
  .popup__body
    %span.label.centered Вы успешно зарегистрировались как участник

app/views/layouts/popups/_participate.html.haml
.popup#participate
  - if user_signed_in?
    %h2.popup__header Регистрация участника
    .popup__body
      = form_tag participate_path, remote: true, method: :post, :'data-type' => :json do
        .field
          %label.label{:for => "register-desc"} Расскажите немного о себе
          .input__wrap
            %textarea#register-desc.textarea{:name => "message"}
        .submit
          %button.button{:type => "submit"} Вступить
  - else
    = render 'layouts/popups/register_body', return_to: 'participate'

app/views/layouts/popups/_recommend.html.haml
.popup#recommend
  - if user_signed_in?
    %h2.popup__header Рекомендовать участника
    .popup__body
      = form_tag members_path, remote: true, :method=> :post, :'data-type' => :json do
        .field
          %label.label{:for => "register-url"} Ссылка на страницу в социальной сети
          .input__wrap
            %input#recommend-url.input{:name => "url", :type => "text"}
        .field
          %label.label{:for => "register-desc"} Расскажите немного об этом человеке
          .input__wrap
            %textarea#recommend-desc.textarea{:name => "message"}
        .submit
          %button.button{:type => "submit"} Рекомендовать
  - else
    = render 'layouts/popups/register_body', return_to: 'recommend'

app/views/layouts/popups/_register.html.haml
.popup#register
  = render 'layouts/popups/register_body', return_to: 'community'

app/views/layouts/popups/_register_body.html.haml
- return_to ||= nil
%h2.popup__header Вход через социальную сеть
.popup__body
  %form{:action => "/", :method => "post"}
    .field
      %span.label.centered Войдите, чтобы иметь возможность проголосовать, стать участником или порекомендовать друга.
      %ul.socialbuttons
        %li.socialbuttons__item
          %a.vk{:href => user_omniauth_authorize_path(:vkontakte, return_to: return_to)}
        %li.socialbuttons__item
          %a.fb{:href => user_omniauth_authorize_path(:facebook, return_to: return_to)}