config/routes.rb
Foresight::Application.routes.draw do
  devise_for  :users,
              controllers: {omniauth_callbacks: "users/omniauth_callbacks"},
              sign_out_via: [:delete, :get]

  match 'rating' => 'start#rating'

  resources :members, :only => [:index, :create, :destroy, :show] do
    member do
      post 'vote'
      post 'activate'
    end
  end

  get "layout"=> 'start#layout'
  post "participate" => 'members#participate'

  get "/scenarios/:scenario" => redirect('/#scenarios')

  root :to => 'start#index'

end

app/controllers/start_controller.rb
class StartController < ApplicationController

  layout "main"

  def index
    @with_register = true
  end

  def secret
    @with_register = true
  end

  def layout
    @with_register = true
  end

  def rating
    render partial: 'rating'
  end


end

app/helpers/start_helper.rb
module StartHelper
end

app/views/start/_rating.html.haml
- if user_signed_in?
  %ul
    - members_rating.each do |m|
      %li<
        = image_tag m.photo, style: 'width: 50px; height: 50px'
        %span.member_name<
          = m.name
        %span.member_rating<
          = m.rating
        %span.vk_like{id: "vk_like_#{m.id}", :"data-id" => m.id, :"data-image" => m.photo}
        %span.fb_like
          %fb:like{href: "#{request.host}/members/#{m.id}", width: 450, send: "false", layout: "button_count", show_faces: "false"}
        - if current_user.members.include? m
          = "Вы уже проголосовали за этого человека"
        - else
          = link_to "Голосовать", vote_member_path(m), remote: true, method: :post, :"data-type" => :json, class: 'vote_link'
        - if can? :manage, m
          = link_to "Активировать", activate_member_path(m), remote: true, method: :post, :"data-type" => :json, class: 'activate_link'
          = link_to "Удалить", member_path(m), remote: true, method: :delete, :"data-type" => :json, class: 'destroy_link', confirm: 'Вы уверены?'
          = link_to "Добавить ссылку на другую сеть"

app/views/start/index.html.haml
- content_for :sections do
  = render 'layouts/sections/main'
  = render 'layouts/sections/scenarios'
  / = render 'layouts/sections/about'
  / = render 'layouts/sections/idea'
  / = render 'layouts/sections/experts', experts: experts
  / = render 'layouts/sections/community'
  = render 'layouts/sections/orgs'
  = render 'layouts/sections/partners'

app/views/start/layout.html.haml
- content_for :sections do
  = render 'layouts/sections/main'
  = render 'layouts/sections/about'
  = render 'layouts/sections/idea'
  = render 'layouts/sections/experts', experts: experts
  = render 'layouts/sections/com'
  = render 'layouts/sections/orgs'
  = render 'layouts/sections/partners'

app/views/start/secret.html.haml
- content_for :sections do
  = render 'layouts/sections/main'
  = render 'layouts/sections/about'
  = render 'layouts/sections/idea'
  = # render 'layouts/sections/experts', experts: experts
  = render 'layouts/sections/community'
  = render 'layouts/sections/orgs'
  = render 'layouts/sections/partners'