config/routes.rb
Foresight::Application.routes.draw do
  devise_for  :users,
              controllers: {omniauth_callbacks: "users/omniauth_callbacks"},
              sign_out_via: [:delete, :get]

  match 'rating' => 'start#rating'

  resources :members, :only => [:index, :create, :destroy, :show] do
    member do
      post 'vote'
      post 'activate'
    end
  end

  get "layout"=> 'start#layout'
  post "participate" => 'members#participate'

  get "/scenarios/:scenario" => redirect('/#scenarios')

  root :to => 'start#index'

end

app/views/layouts/sections/_about.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "about"} Идея
%a.flag{:name => "about"}
%section.section.about#about
  .section__wrap
    %table.about__main_wrap{:cellpadding => "0", :cellspacing => "0"}
      %tr
        %td.about__main_before
          .about__main_before_wrap  
        %td.about__main
          %h2.section__header Идея проекта
          .section__text.usercontent
            %p
              200 активных жителей нашего города разных возрастов и профессий при поддержке ведущих федеральных экспертов примут участие в 
              %nobr 3-дневной
              %strong форсайт-сессии.
              Это специальный формат коллективной умственной работы, продукт которого — сценарии развития, образы будущего и дорожная карта по достижению желаемого состояния рассматриваемого объекта. В данном случае — города Красноярска.
            %p
              %strong Технология «Форсайт»,
              от английского foresight — взгляд в будущее, применяется в современном мире в целях мобилизации интеллектуальных ресурсов активных граждан для качественного прорыва в какой-либо проблемной области.
            %p Мы считаем, что необходимо использовать эту технологию для объединения здоровых сил общества и достижения позитивных изменений в жизни своего города.
            %p Важно: катастрофический, а, тем более, апокалиптический сценарий развития мы во внимание не берем, так как на его основе невозможно действовать.
            %h3 Цели
            %ul
              %li Анализ существующих трендов и ресурсов;
              %li Обсуждение видения будущего города Красноярска до 2030 года;
              %li Оформление 3-5 альтернативных сценариев развития города;
              %li Построение дорожной карты.
          .fulldescription
            %a.button{href: '/foresight.pdf', style: 'text-decoration:none', target: '_blank'}
              %span.button__wrap Скачать полное описание
              %span.button__subtext PDF (0.3 МБ)
          %h2.section__header Стать участником
          .section__text.usercontent{:style => "columns:1;-webkit-columns:1;-moz-columns:1;"}
            .column
              %p
                %strong Состав участников форсайт-сессии формируется по трем направлениям:
              %ol
                %li 50 профессионалов по персональным приглашениям: эксперты в области урбанистики, бизнеса, управления, публичные персоны, представители профильных ведомств и общественных организаций;
                %li
                  50 наиболее активных участников четырех предварительных тематических встреч (экспертных сессий) по направлениям: экономика, управление, инфраструктура, культурно-образовательная среда.
                  %a{:href => "#idea"} Расписание
                %li
                  100 ведущих представителей сетевого сообщества Красноярска, выбранных
                  %a{:href => "#community"} голосованием
                  на сайте  проекта.
            .column
              %p
                %strong Чтобы принять участие в проекте вам необходимо:
              %ol
                %li
                  Пройти онлайн регистрацию , заполнив
                  %a{:href => 'https://docs.google.com/spreadsheet/viewform?formkey=dGJTRk1FMzE4MDVXVDhMRTBiUmQ1THc6MQ#gid=0', :target => "_blank"} анкету
                %li
                  Определиться с форматом участия и сделать следующее:
                  %ol
                    %li Для экспертов — связаться с оргкомитетом для аккредитации;
                    %li Для участников экспертных сессий — ознакомиться с расписанием и посетить их;
                    %li
                      Для активистов онлайн сообщества, как, впрочем, и для всех остальных, —
                      %span.pseudolink.js_popup{"data-rel" => 'register'} авторизоваться
                      на сайте проекта и позаботиться о поддержке своих друзей и знакомых.
          .fulldescription
            %a.button{href: 'https://docs.google.com/spreadsheet/viewform?formkey=dGJTRk1FMzE4MDVXVDhMRTBiUmQ1THc6MQ#gid=0', style: 'text-decoration:none', target: '_blank'} Анкета участника
        %td.about__main_after
          .about__main_after_wrap  
  .section__helper

app/views/layouts/sections/_community.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "community"} Сообщество
%a.flag#community{:name => "community"}
%section.section.community
  .section__wrapper
    .section__wrap
      %h2.section__header Foresight-сообщество
      .section__text.usercontent
        %p Красноярское форсайт-сообщество — это мы, кому небезразлично будущее родного города.
        -#
          %p Любой активный житель города на этом сайте может:
          %ul
            %li Вступить в сообщество и самому претендовать на участие в форсайт-сессии.
            %li Предложить достойного, по его мнению, кандидата для участия в форсайт-сессии
        -#.community__join
          - unless (user_signed_in? && current_user.member.present?)
            %span#participate_btn.button.contour.js_popup{"data-rel" => "participate"} Вступить в сообщество
          %span.button.contour.js_popup{"data-rel" => "recommend"} Порекомендовать в сообщество
      .community__top
        .community__top_header ТОП-10
        .community__top_body
          %ol.members
            = render 'layouts/sections/members', all:false
        .community__allmembers
          = link_to 'Показать весь список', members_path, method: :get, remote: true, id: 'allmembers_link', class: 'button violet'
    .section__helper
  .community__triangle

app/views/layouts/sections/_experts.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "experts"} Эксперты
%a.flag{:name => "experts"}
%section.section.experts#experts
  .section__wrapper
    .section__wrap
      %h2.section__header Эксперты
      .sliderexperts
        .sliderexperts__wrap
          %ul.sliderexperts__list
            - experts.each do |e|
              %li.sliderexperts__item
                .expert
                  .expert__main
                    /
                      div class="expert__photo_wrap">
                      <img src="content/expert-1.jpg" width="204" height="153" alt="" class="expert__photo">
                      </div
                    .expert__photo_wrap
                      %img.expert__photo{src: e[:img], width: 204, height: 153}
                    .expert__name= e[:name]
                    .expert__role= e[:role]
                  %footer.expert__footer
                    = link_to e[:web], "http://#{e[:web]}", class: "expert__web" if e[:web]
                    %ul.expert__social
                      - if e[:vk_url]
                        %li.expert__social_item
                          %a.expert__social_link.vk{:href => e[:vk_url], :target => "_blank"} Вконаткте
                      - if e[:fb_url]
                        %li.expert__social_item
                          %a.expert__social_link.fb{:href => e[:fb_url], :target => "_blank"} Фейсбук
        .sliderexperts__control
          .sliderexperts__prev
          .sliderexperts__next
      .sliderkrskexperts
        .sliderkrskexperts__wrap
          %ul.sliderkrskexperts__list
            - krskexperts.each do |e|
              %li.sliderkrskexperts__item
                .expert
                  .expert__main
                    /
                      div class="expert__photo_wrap">
                      <img src="content/expert-1.jpg" width="204" height="153" alt="" class="expert__photo">
                      </div
                    .expert__photo_wrap
                      %img.expert__photo{src: e[:img], width: 204, height: 153}
                    .expert__name= e[:name]
                    .expert__role= e[:role]
                  %footer.expert__footer
                    = link_to e[:web], "http://#{e[:web]}", class: "expert__web" if e[:web]
                    %ul.expert__social
                      - if e[:vk_url]
                        %li.expert__social_item
                          %a.expert__social_link.vk{:href => e[:vk_url], :target => "_blank"} Вконаткте
                      - if e[:fb_url]
                        %li.expert__social_item
                          %a.expert__social_link.fb{:href => e[:fb_url], :target => "_blank"} Фейсбук
        .sliderkrskexperts__control
          .sliderkrskexperts__prev
          .sliderkrskexperts__next
    .section__helper
  .experts__triangle

app/views/layouts/sections/_idea.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "idea"} Расписание
%a.flag{:name => "idea"}
%section.section.idea#idea
  .section__wrap
    %h2.section__header Дата и время проведения
    .section__text.usercontent
      %p В рамках проекта Красноярск FORESIGHT состоится:
      %ol
        %li Четыре подготовительные экспертные сессии по 2-3 часа: доклады экспертов по проблематике, работа в группах, обсуждение.
        %li Основное мероприятие — трехдневная форсайт сессия в библиотеке СФУ.
      %table
        %tr
          %th{:width => "460"} Мероприятие
          %th Дата и время
          %th Место
        %tr
          %td Экономика города: индустриальное прошлое и неизвестное будущее
          %td
            6 ноября, 17:00-20:00
          %td
            Актовый зал КРИТБИ
            %br
            пр. Свободный, 75
        %tr
          %td Управление городом: власть, бизнес и городские сообщества
          %td
            9 ноября, 17:00-20:00
          %td
            Библиотека СФУ, ауд. 4-11
            %br
            пр. Свободный, 79/10
        %tr
          %td Образ города: архитектура, градостроительство, инфраструктура
          %td
            12 ноября, 17:00-20:00
          %td
            Актовый зал КРИТБИ
            %br
            пр. Свободный, 75
        %tr
          %td Культурно-образовательное  пространство города: культура, наука, образование, инноватика
          %td
            14 ноября, 17:00-20:00
          %td
            Актовый зал КРИТБИ
            %br
            пр. Свободный, 75
        %tr
          %td
            %strong Форсайт-сессия по формированию образа будущего города Красноярска
          %td
            %div
              17,18 ноября, 11:00-19:00
            %div
              19 ноября, 14:00-19:00
          %td
            Библиотека СФУ
            %br
            пр. Свободный, 79/10
  .section__helper

app/views/layouts/sections/_main.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "book"} Книга

%a.flag{:name => "main"}
%section.section.main#main
  .section__wrap
    %iframe{:allowfullscreen => "", :frameborder => "0", :height => "400", :mozallowfullscreen => "", :src => "http://player.vimeo.com/video/59477072", :webkitallowfullscreen => "", :width => "600"}
  .section__helper

%a.flag{:name => "book"}
%section.section.book#book
  .section__wrap
    .slogan{style: 'margin-top:20px'} Проектируем будущее вместе!
    %a.button{href: '/foresight_book.pdf', style: 'text-decoration:none; margin-top: 50px', target: '_blank'}
      %span.button__wrap Скачать книгу КРАСНОЯРСК FORESIGHT
      %span.button__subtext PDF (4.9 МБ)
  .section__helper

app/views/layouts/sections/_members.html.haml
- members_rating(all).each do |m|
  %li.members__item>
    .member
      .member__photo_wrap
        %img.member__photo{:alt => "", :height => "90", :src => m.photo, :width => "90"}
        %span.member__count= m.rating
      .member__name
        = m.first_name
        %br
        = m.last_name
      =#.member__desc Управленец, предприниматель
      .member__share
        =#Place for share buttons
        - if can? :manage, m
          = link_to "Удалить", member_path(m), remote: true, method: :delete, :"data-type" => :json, class: 'destroy_link', confirm: 'Вы уверены?'
      %footer.member__footer
        %ul.member__social
          - if m.has_vkontakte?
            %li.member__social_item
              %a.vk{:href => m.vkontakte_url, target: 'blank'} Вконтакте
          - if m.has_facebook?
            %li.member__social_item
              %a.fb{:href => m.facebook_url, target: 'blank'} Фейсбук

        -# if !user_signed_in?
          %span.js_popup.button.vote{"data-rel" => "register"} Поддержать
          =# link_to "Поддержать", '#', class: 'js_popup button vote'
        -# if user_signed_in? && !(current_user.members.include? m)
          = link_to "Поддержать", vote_member_path(m), remote: true, method: :post, :"data-type" => :json, class: 'button vote'

app/views/layouts/sections/_orgs.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "orgs"} Команда
%a.flag{:name => "orgs"}
%section.section.orgs#orgs
  .section__wrapper
    .section__wrap
      %h2.section__header Команда проекта
      .sliderpartners.sliderorgs
        .sliderpartners__wrap
          %ul.sliderpartners__list
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/kryukov.png"}
                .orgs__name Иван Крюков
                .orgs__desc Стратегический маркетолог, специалист по цифровому маркетингу и политическому PR в сети. Интернет-предприниматель.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/okruh.png"}
                .orgs__name Станислав Окрух
                .orgs__desc Дизайнер и предприниматель. Основатель и креативный директор агентства брендинга и интерактивного дизайна «SmartHeart».
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/urazov.png"}
                .orgs__name Максим Уразов
                .orgs__desc Руководитель управления молодёжной политики администрации города Красноярска.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/dadasheva.png"}
                .orgs__name Вера Дадашева
                .orgs__desc Аналитик, методист, ведущий специалист Центра стратегических исследований и разработок СФУ.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/khvostenko.png"}
                .orgs__name Алексей Хвостенко
                .orgs__desc Аналитик, автор текстов, частный консультант по маркетингу и управлению проектами. Руководитель проекта «Красноярский креативный кампус».
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/gureeva.png"}
                .orgs__name Татьяна Гуреева
                .orgs__desc Специалист по связям с общественностью управления молодёжной политики Администрации г. Красноярска. Официальный представитель сайта kmforum.ru
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/myasnikov.png"}
                .orgs__name Сергей Мясников
                .orgs__desc Специалист по коммуникационным кампаниям и маркетингу в соцсетях, топовый блогер, посол Livejournal в Красноярске.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/dozortsev.png"}
                .orgs__name Илья Дозорцев
                .orgs__desc Главный специалист управления молодежной политики администрации г. Красноярска.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/branchukov.png"}
                .orgs__name Денис Бранчуков
                .orgs__desc Юрист управления молодежной политики г. Красноярска
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/loginova.png"}
                .orgs__name Юлия Логинова
                .orgs__desc Главный специалист-экономист управления молодежной политики администрации г. Красноярска.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/gulyutin.png"}
                .orgs__name Николай Гулютин
                .orgs__desc Исследователь современных социальных и политических процессов, аналитик Центра «НЭРА – Новая Экономическая Реальность».
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/gaidamak.png"}
                .orgs__name Дина Гайдамак
                .orgs__desc Психолог-консультант, руководитель направления «Личностный рост» клуба «Сибирский социон», специалист в области рекламы.
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/ladyzhenko.png"}
                .orgs__name Сергей Ладыженко
                .orgs__desc Директор Центра молодежных инициатив «Форум»
            %li.sliderpartners__item>
              .orgs
                .orgs__photo
                  %img.orgs__photo_image{:alt => "", :src => "/assets/orgs/chihacheva.png"}
                .orgs__name Татьяна Чихачева
                .orgs__desc Менеджер государственных программ и бизнес-проектов. Специалист по кадрам
        .sliderorgs__control
          .sliderorgs__prev
          .sliderorgs__next
    .section__helper

app/views/layouts/sections/_partners.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "partners"} Учредители и партнеры
%a.flag{:name => "partners"}
%section.section.partners#partners
  .section__wrapper
    .section__wrap
      %h2.section__header Учредители и партнеры
      .sliderpartners
        %ul.sliderpartners__list
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://admkrsk.ru", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/adm.png"}
                .partner__helper
              .partner__desc Администрация города Красноярска
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://kmforum.ru", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/kmf.png"}
                .partner__helper
              .partner__desc Молодежная неделя
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://braincamp.ru", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/cc.png"}
                .partner__helper
              .partner__desc Креативный кампус
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://smart-heart.ru", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/sh.png"}
                .partner__helper
              .partner__desc Агентство дизайна и коммуникаций
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://prima-tv.ru/", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/sts.png"}
                .partner__helper
              .partner__desc СТС-Прима
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://www.kritbi.ru/", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/kritbi.png"}
                .partner__helper
              .partner__desc Красноярский региональный инновационно-технологический бизнес-инкубатор
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://innov.pro/", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/innov.png"}
                .partner__helper
              .partner__desc Инновационный прорыв
          %li.sliderpartners__item
            .partner
              .partner__logo
                %img.partner__logo_image{:alt => "", :src => "/assets/logos/itk.png"}
                .partner__helper
              .partner__desc Информационные терминалы Красноярск
          %li.sliderpartners__item
            .partner
              .partner__logo
                %a.partner__logo_link{:href => "http://foresight.sfu-kras.ru/", :target => "_blank"}
                  %img.partner__logo_image{:alt => "", :src => "/assets/logos/scir.png"}
                .partner__helper
              .partner__desc Центр стратегических исследований и разработок СФУ
        .sliderpartners__control
          .sliderpartners__prev
          .sliderpartners__next
    .section__helper

app/views/layouts/sections/_scenarios.html.haml
- content_for :menu do
  %li.sitenav__item
    %span.sitenav__link{"data-href" => "scenarios"} Сценарии развития
%a.flag{:name => "scenarios"}
%section.section.scenarios#scenarios
  .section__wrapper
    .section__wrap
      %h2.section__header Выбери сценарий развития города
      .sliderscenarios.sliderorgs
        .sliderscenarios__wrap
          %ul.sliderscenarios__list
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/global_city.jpg"}
                = render "scenarios/vote", scenario: "global_city"
                .scenarios__meta
                  .scenarios__name Глобальный город Сибири
                  .scenarios__desc Красноярск — это ворота для мирового капитала и новых технологий. Он открывает Сибирь миру, а мир Сибири. Для этого он должен стать многоязычным городом, глобальным логистическим узлом и центром международного сотрудничества.
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/oasis.jpg"}
                = render "scenarios/vote", scenario: "oasis"
                .scenarios__meta
                  .scenarios__name Оазис комфорта
                  .scenarios__desc Красивый, интересный, удобный город. Ориентированный, в первую очередь, на горожан, а не на промышленные производства. В условиях усиливающейся конкуренции городов за человеческий капитал, Красноярск должен сконцентрироваться на повышении качества жизни: улучшать экологию, развивать общественный транспорт и социальную сферу.
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/kras_vegas.jpg"}
                = render "scenarios/vote", scenario: "kras_vegas"
                .scenarios__meta
                  .scenarios__name Крас-Вегас
                  .scenarios__desc Центр потребления и рекреации для работников сырьевых и промышленных компаний близлежащих регионов. Создание в городе игорной зоны и комплексное развитие индустрии въездного туризма позволит Красноярску стать развлекательным центром Сибири.
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/technopolis.jpg"}
                = render "scenarios/vote", scenario: "technopolis"
                .scenarios__meta
                  .scenarios__name Технополис
                  .scenarios__desc Инженерный и внедренческий центр международного уровня, центр современного, высокотехнологичного производства. В городе должно поддерживаться создание технопарков и комплексов прототипирования, R&D центров крупных компаний. Должны развиваться наука и образование.
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/north_frontir.jpg"}
                = render "scenarios/vote", scenario: "north_frontir"
                .scenarios__meta
                  .scenarios__name Северный фронтир
                  .scenarios__desc Красноярск — центр разработки и внедрения новых технологий и практик, связанных с жизнью и деятельностью в суровых климатических условиях. Для этого город должен стать плацдармом освоения Арктики и центром нового осмысления жизни человека в условиях Севера.
            %li.sliderscenarios__item>
              .scenarios
                .scenarios__photo
                  %img.scenarios__photo_image{:alt => "", :src => "/assets/scenarios/sib_detroit.jpg"}
                = render "scenarios/vote", scenario: "sib_detroit"
                .scenarios__meta
                  .scenarios__name Сибирский Детройт
                  .scenarios__desc Это депрессивный сценарий, основан на возможности серьезного экономического кризиса. По аналогии с американским Детройтом, который в результате падения уровня производства стали массово покидать люди.
        .sliderscenarios__control
          .sliderscenarios__prev
          .sliderscenarios__next
    .section__helper